/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PQtgGPYs6Nt
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

"use client";
import { ChangeEvent, FormEvent, useState } from "react";
import { IconProps } from "@radix-ui/react-icons/dist/types";
import Button from "./Button";
import Image from "next/image";

export function Upload() {
  const [file, setFile] = useState<File | undefined>();
  const [uploading, setUploading] = useState<boolean>(false);
  const [message, setMessage] = useState<string>("");
  const [preview, setPreview] = useState<string | null>(null);

  const handleFileChange = async (event: ChangeEvent<HTMLInputElement>) => {
    if (event.target.files && event.target.files.length > 0) {
      const uploadedFile = event.target.files?.[0];
      setFile(uploadedFile);
      let reader = new FileReader();

      reader.onloadend = () => {
        setPreview(reader.result as string);
      };
      reader.readAsDataURL(uploadedFile);
    }
    setMessage("");
  };

  const handleWorkerApiSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (file) {
      setUploading(true);
      setMessage("Uploading...");
      const formData = new FormData();
      formData.append("file", file);

      try {
        const res = await fetch(
          `/api/workers-api/upload?filename=${file.name}`,
          {
            method: "PUT",
            body: formData,
          }
        );

        const result = (await res.json()) as { status: string };
        result.status === "success"
          ? setMessage("File Upload Successful")
          : setMessage("File Upload Failed");
      } catch (error) {
        setMessage("An error occured");
      } finally {
        setUploading(false);
      }
    } else {
      setMessage("Please select a file");
    }
  };

  const handlePreSignedUrlSubmit = async (
    event: FormEvent<HTMLFormElement>
  ) => {
    event.preventDefault();
    if (file) {
      setUploading(true);
      setMessage("Uploading...");
      try {
        // Fetch the Pre-Signed URL
        const res = await fetch("/api/pre-signed", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ filename: file.name }),
        });
        if (res.ok) {
          const { url }: { url: string } = await res.json();
          const uploadRes = await fetch(url, {
            method: "PUT",
            body: file,
          });
          console.log(uploadRes);
          if (uploadRes.ok) {
            setMessage("File Upload Successful!");
          } else {
            setMessage("File Upload Failed");
          }
        } else {
          setMessage("Pre-Sign URL error");
        }
      } catch (error) {
        console.error(error);
        setMessage("An error occured");
      } finally {
        setUploading(false);
      }
    } else {
      setMessage("Please select a file");
    }
  };

  const handleTempCredsSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (file) {
      setUploading(true);
      setMessage("Uploading...");
      try {
        // Fetch the Pre-Signed URL
        const res = await fetch("/api/temp-creds", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ filename: file.name }),
        });
        if (res.ok) {
          const { url }: { url: string } = await res.json();
          const uploadRes = await fetch(url, {
            method: "PUT",
            body: file,
          });
          console.log(uploadRes);
          if (uploadRes.ok) {
            setMessage("File Upload Successful!");
          } else {
            setMessage("File Upload Failed");
          }
        } else {
          setMessage("Pre-Sign URL error");
        }
      } catch (error) {
        console.error(error);
        setMessage("An error occured");
      } finally {
        setUploading(false);
      }
    } else {
      setMessage("Please select a file");
    }
  };

  return (
    <main className="flex flex-col items-center justify-center h-screen bg-gradient-to-b from-gray-50 to-gray-200 dark:from-gray-800 dark:to-gray-900">
      <div className="w-full max-w-3xl p-6 md:p-8 lg:p-10">
        <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-lg transition-transform hover:scale-105 duration-300">
          <div className="p-6 md:p-8 lg:p-10">
            <h1 className="text-3xl font-extrabold mb-6 dark:text-gray-200 text-center">
              Upload Your Image
            </h1>
            <form>
              <div className="flex justify-center items-center h-64 bg-gradient-to-r from-gray-200 to-gray-300 dark:from-gray-700 dark:to-gray-600 rounded-lg mb-6 border-2 border-dashed border-gray-300 dark:border-gray-600">
                <label
                  className="cursor-pointer flex flex-col items-center justify-center space-y-3 text-gray-600 dark:text-gray-400 hover:text-gray-800 dark:hover:text-gray-200 transition-colors"
                  htmlFor="image-upload"
                >
                  <UploadIcon className="w-10 h-10 text-gray-400 dark:text-gray-500 hover:text-gray-600 dark:hover:text-gray-300" />
                  <span className="font-medium">
                    Drag and drop or click to upload
                  </span>
                </label>
                <input
                  accept="image/*"
                  className="hidden"
                  id="image-upload"
                  type="file"
                  onChange={handleFileChange}
                />
              </div>

              {preview && (
                <div className="bg-white dark:bg-gray-800 shadow-lg mt-6 mb-4 rounded-lg overflow-hidden transition-all">
                  <Image
                    src={preview}
                    alt="Uploaded Image"
                    width={600}
                    height={400}
                    className="w-full h-auto"
                  />
                </div>
              )}

              <div className="text-center mb-4">
                <p className="text-lg dark:text-gray-200 font-semibold">
                  Upload with
                </p>
                <p className="text-sm text-gray-500 dark:text-gray-400 mb-4">
                  Select one method
                </p>
              </div>

              <div className="flex justify-between gap-4">
                <Button
                  text="Workers API"
                  submitHandler={handleWorkerApiSubmit}
                  className="bg-blue-500 hover:bg-blue-600 dark:bg-blue-600 dark:hover:bg-blue-700 text-white font-medium px-4 py-2 rounded-lg shadow-md transition-all duration-200"
                />
                <Button
                  text="Pre-signed URL"
                  submitHandler={handlePreSignedUrlSubmit}
                  className="bg-green-500 hover:bg-green-600 dark:bg-green-600 dark:hover:bg-green-700 text-white font-medium px-4 py-2 rounded-lg shadow-md transition-all duration-200"
                />
                <Button
                  text="Temp Credentials"
                  submitHandler={handleTempCredsSubmit}
                  className="bg-purple-500 hover:bg-purple-600 dark:bg-purple-600 dark:hover:bg-purple-700 text-white font-medium px-4 py-2 rounded-lg shadow-md transition-all duration-200"
                />
              </div>
            </form>

            <div className="mt-4">
              <p className="text-gray-600 dark:text-gray-400 italic">
                {message}
              </p>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}

function UploadIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  );
}
